spring:
  liquibase:
    change-log: classpath:db/liquibase-changelog.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: password
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false

server:
  port: ${ES_BACKEND_PORT:8080}
